#!/usr/bin/env python
# This file is automatically generated by pywf script
# based on the content in pyproject.toml file

__version__ = "0.2.0"
__short_description__ = "Open-source audio-to-text transcription library wrapping faster-whisper with VAD-aware chunking and batched inference."
__license__ = "MIT"
__author__ = "Sanhe Hu"
__author_email__ = "husanhe@email.com"
__maintainer__ = "Sanhe Hu"
__maintainer_email__ = "husanhe@email.com"

# run this script to print out the version number
if __name__ == "__main__":  # pragma: no cover
    print(__version__)
